### ISSUE TITLE
fbthrift fails to build due to folly, wangle issue

### ISSUE THREAD

**Issue by sneiman** [facebook/fbthrift#129]
I have been building and using flbualib for a long time, but on a new install have found that it will not build due to a folly/wangle problem.

On Ubuntu 14.04 lts. All paths look good, folly is clearly installed - used ./build/deps_ubuntu_14.04.sh for dependencies. During ./configure for fbthrift, asked to install wangle from github. downloaded, etc.

Following wangle instructions:

sneiman@chimp:~/dev/wangle/wangle$ make
[  2%] Building CXX object CMakeFiles/wangle.dir/acceptor/AcceptorHandshakeHelper.cpp.o
/home/sneiman/dev/wangle/wangle/acceptor/AcceptorHandshakeHelper.cpp: In member function ‘virtual void wangle::AcceptorHandshakeHelper::handshakeSuc(folly::AsyncSSLSocket*)’:
/home/sneiman/dev/wangle/wangle/acceptor/AcceptorHandshakeHelper.cpp:52:34: error: ‘class folly::AsyncSSLSocket’ has no member named ‘getSSLCertSigAlgName’
   const char* sigAlgName = sock->getSSLCertSigAlgName();
                                  ^
/home/sneiman/dev/wangle/wangle/acceptor/AcceptorHandshakeHelper.cpp:66:43: error: ‘class folly::AsyncSSLSocket’ has no member named ‘getSSLClientSigAlgs’
       std::make_shared<std::string>(sock->getSSLClientSigAlgs());
                                           ^
make[2]: *** [CMakeFiles/wangle.dir/acceptor/AcceptorHandshakeHelper.cpp.o] Error 1
make[1]: *** [CMakeFiles/wangle.dir/all] Error 2
make: *** [all] Error 2

Unfortunately, this is a show stopper for me. If you could give me any ideas for what I am missing, or a workaround or when it might be fixed, it would be greatly appreciated.

thanks,
seth

**Comment by roticv** [comment]
Can you pull the latest folly? This is fixed in https://github.com/facebook/folly/commit/f7176051f816980a985beeb9b8a907dddd0dc0e3

**Comment by sneiman** [comment]
Will do.

This entire message is confidential. If it isn't intended for you, you may not use it – so please throw it away and forget about it.

**Comment by sneiman** [comment]
better but not home yet. a few comments: the ubuntu14.04 dependency build script apparently does not pull the correct version of folly. I did it by hand, included gtest, built it, then built wangle, and cloned fbthrift. I did NOT use the dep script as noted, but just ran the autoconf, etc sequence.During the make phase:

In file included from /usr/include/c++/4.8/memory:81:0,
                 from /usr/local/include/folly/io/async/AsyncTimeout.h:27,
                 from /usr/local/include/folly/io/async/HHWheelTimer.h:19,
                 from ../../../thrift/lib/cpp/async/HHWheelTimer.h:19,
                 from ../../../thrift/lib/cpp2/async/HeaderClientChannel.h:20,
                 from async/HeaderClientChannel.cpp:17:
/usr/include/c++/4.8/bits/unique_ptr.h: In instantiation of 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = wangle::StaticPipeline<folly::IOBufQueue&, std::pair<std::unique_ptr<folly::IOBuf>, apache::thrift::transport::THeader*>, apache::thrift::TAsyncTransportHandler, wangle::OutputBufferingHandler, apache::thrift::ProtectionHandler, apache::thrift::FramingHandler, apache::thrift::Cpp2Channel>; _Dp = folly::DelayedDestruction::Destructor]':
../../../thrift/lib/cpp2/async/Cpp2Channel.h:62:27:   required from here
/usr/include/c++/4.8/bits/unique_ptr.h:184:16: error: no match for call to '(std::unique_ptr<wangle::StaticPipeline<folly::IOBufQueue&, std::pair<std::unique_ptr<folly::IOBuf>, apache::thrift::transport::THeader*>, apache::thrift::TAsyncTransportHandler, wangle::OutputBufferingHandler, apache::thrift::ProtectionHandler, apache::thrift::FramingHandler, apache::thrift::Cpp2Channel>, folly::DelayedDestruction::Destructor>::deleter_type {aka folly::DelayedDestruction::Destructor}) (wangle::StaticPipeline<folly::IOBufQueue&, std::pair<std::unique_ptr<folly::IOBuf>, apache::thrift::transport::THeader*>, apache::thrift::TAsyncTransportHandler, wangle::OutputBufferingHandler, apache::thrift::ProtectionHandler, apache::thrift::FramingHandler, apache::thrift::Cpp2Channel>*&)'
    get_deleter()(__ptr);
                ^
In file included from /usr/local/include/folly/io/async/HHWheelTimer.h:20:0,
                 from ../../../thrift/lib/cpp/async/HHWheelTimer.h:19,
                 from ../../../thrift/lib/cpp2/async/HeaderClientChannel.h:20,
                 from async/HeaderClientChannel.cpp:17:
/usr/local/include/folly/io/async/DelayedDestruction.h:69:9: note: candidate is:
   class Destructor {
         ^
/usr/local/include/folly/io/async/DelayedDestruction.h:71:10: note: void folly::DelayedDestruction::Destructor::operator()(folly::DelayedDestruction*) const
     void operator()(DelayedDestruction* dd) const {
          ^
/usr/local/include/folly/io/async/DelayedDestruction.h:71:10: note:   no known conversion for argument 1 from 'wangle::StaticPipeline<folly::IOBufQueue&, std::pair<std::unique_ptr<folly::IOBuf>, apache::thrift::transport::THeader*>, apache::thrift::TAsyncTransportHandler, wangle::OutputBufferingHandler, apache::thrift::ProtectionHandler, apache::thrift::FramingHandler, apache::thrift::Cpp2Channel>*' to 'folly::DelayedDestruction*'
make[5]: *** [async/libthriftcpp2_la-HeaderClientChannel.lo] Error 1
make[5]: Leaving directory `/home/sneiman/dev/fbthrift/thrift/lib/cpp2'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/sneiman/dev/fbthrift/thrift/lib/cpp2'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/sneiman/dev/fbthrift/thrift/lib/cpp2'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/sneiman/dev/fbthrift/thrift/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/sneiman/dev/fbthrift/thrift'
make: *** [all] Error 2
sneiman@chimp:~/dev/fbthrift/thrift$ 


There is a small possibility that this machine has some conflicting versions of boost on it, If you think that might be causing this, I will tear it apart and try again.

**Comment by lixiangnlp** [comment]
I also met the problem. Do you have any solutions?

**Comment by sneiman** [comment]
My problem was resolved when I fixed a conflict in the boost installation on the target machine. Turned out it was part 1.54 and part 1.56. after that I cleaned up all the remnants of the earlier installation attempts, and then the installation went fine.

Sent from mobile device - sorry for typos and brevity.

This entire message is confidential. If it isn't intended for you, you may not use it - so please throw it away and forget about it.

On Nov 8, 2015, at 7:01 PM, Xiang Li <notifications@github.com<mailto:notifications@github.com>> wrote:


I also met the problem. Do you have any solutions?

**Comment by lixiangnlp** [comment]
@sneiman  I have cleaned up the old boost in my machine. Currently the boost version is 1.59. But the problem still exists. 

I also can not compile wangle successfully, although the libwangle.a is produced. The error is as the following. I do not know whether it is the reason of thrift fails.

[ 53%] Building CXX object CMakeFiles/wangle.dir/concurrent/IOThreadPoolExecutor.cpp.o
[ 55%] Building CXX object CMakeFiles/wangle.dir/concurrent/ThreadPoolExecutor.cpp.o
[ 57%] Building CXX object CMakeFiles/wangle.dir/deprecated/rx/Dummy.cpp.o
[ 59%] Building CXX object CMakeFiles/wangle.dir/ssl/PasswordInFile.cpp.o
[ 61%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLContextManager.cpp.o
[ 63%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLSessionCacheManager.cpp.o
[ 65%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLUtil.cpp.o
[ 68%] Building CXX object CMakeFiles/wangle.dir/ssl/TLSTicketKeyManager.cpp.o
Linking CXX static library lib/libwangle.a
[ 68%] Built target wangle
Scanning dependencies of target AcceptorTest
[ 70%] Building CXX object CMakeFiles/AcceptorTest.dir/acceptor/test/AcceptorTest.cpp.o
Linking CXX executable bin/AcceptorTest
/usr/bin/ld: gmock/src/gmock-build/libgmock.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [bin/AcceptorTest] error 1
make[1]: *** [CMakeFiles/AcceptorTest.dir/all] error 2
make: *** [all] error 2

**Comment by sneiman** [comment]
Sorry – this is outside of my experience. I just have built it the one time.

S

This entire message is confidential. If it isn't intended for you, you may not use it – so please throw it away and forget about it.

**Comment by djwatson** [comment]
gmock issue should be fixed in wangle
