### ISSUE TITLE
Make fails on Cenots 7.2

### ISSUE THREAD

**Issue by apepojken** [facebook/fbthrift#167]
Trying to build fbthrift on centos 7 fails.
I have copied the output of the commands to: https://github.com/apepojken/Fails/blob/master/fbthrift-fail

I don't get why it's failing. According to ./configure output mstch is working
`checking mstch/mstch.hpp usability... yes
checking mstch/mstch.hpp presence... yes
checking for mstch/mstch.hpp... yes`
But all the build errors seems to stem from something called "t_mstch_swift_generator.cc"

Any help apprecieated!

**Comment by lukenels** [comment]
Hey @apepojken, I'm the author of the diff that introduces this issue, I'm investigating the cause right now and will get back to you soon.

**Comment by apepojken** [comment]
Great! Thank you.

**Comment by lukenels** [comment]
@apepojken Would you mind updating to the latest commit and trying to build again? I believe the problem should be fixed now.

**Comment by apepojken** [comment]
I tried building it the same way. Still didn't work. 
I updated the output in the link above. It still fails on something with "t_mstch_swift_generator.cc" but it's not the same error.

**Comment by lukenels** [comment]
@apepojken Thanks for the update, investigating it now.

**Comment by lukenels** [comment]
Could you try rebuilding and installing the mstch library? I've had issues before that arise from compiling thrift and mstch with different compiler versions resulting in symbol lookup errors. What was the process you used to install mstch?

**Comment by apepojken** [comment]
I tried rebuilding mstch, this is how I did it: https://github.com/apepojken/Fails/blob/master/mstch-build
It still fails but with another error this time: `PYTHONPATH=../../.python-local/lib/python /usr/bin/python -mthrift_compiler.main --gen cpp2 Sasl.thrift
/usr/bin/python: /root/build/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg/thrift_compiler/frontend.so: undefined symbol: _ZN5folly6detail11formatOctalE`

Once again i updated the link above with the output from make.

**Comment by zleho** [comment]
I experience the same issue as apepojken in his last comment. It seems like frontend.so does not have a reference to libfolly.so.

$ ldd  fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg/thrift_compiler/frontend.so | grep folly | wc -l
0

**Comment by byronwwang** [comment]
me too

**Comment by lukenels** [comment]
Thanks for the update. I was hitting this build error as well and had to rebuild and install Folly, which fixed the issue. Could you try rebuilding and installing Folly and trying again?

(NB: If you encounter errors related to `MEMBARRIER_CMD_QUERY` when building folly, check out [this issue](https://github.com/facebook/folly/issues/453) )

**Comment by apepojken** [comment]
I rebuilt/installed Folly, no errors. Tried rebuilding Thrift but got to the same point as earlier. Did the same thing again but this time rebuilt/installed mstch before Thrift. Still the same result.

**Comment by lukenels** [comment]
@apepojken Thanks for keeping me posted. I'm fixing some other build errors with fbthrift right now, and I'm trying to reproduce the exact error you're getting. Would you mine telling me your compiler version and boost version?

**Comment by apepojken** [comment]
Boost 1.60 and gcc version 4.8.5

**Comment by byronwwang** [comment]
I rebuild everything, and still got the same error as @apepojken last mentioned. I'm with boost 1.54 and gcc 4.8.5 and Centos 7.2.
BTW, I still got another error related to the generated Makefile (in 'compiler/py' fold) in Line 'frontend_la_LDFLAGS...'. Since BOOST_PYTHON_LIB is empty, during the compiling,  It's says '/usr/bin/ld: cannot find -l-L/home/byron/utils/python2/lib'

**Comment by zleho** [comment]
I managed to get it compile and link correctly with the attached patch. I am using folly 2016.08.22 tag.
[fbthrift.zip](https://github.com/facebook/fbthrift/files/434265/fbthrift.zip)

**Comment by byronwwang** [comment]
@zleho Great！It works！

**Comment by byronwwang** [comment]
I got a new error during compiling thpp.
![image](https://cloud.githubusercontent.com/assets/6510742/17927660/46d93548-6a29-11e6-9ed7-4fd9f3930d3a.png)

**Comment by apepojken** [comment]
@zleho's patch worked for me too. Thank you, great job!

**Comment by byronwwang** [comment]
I manually and copying the thrift_compiler directory to my python site_packages. It fixed the error.

**Comment by byronwwang** [comment]
An new error again. 

> fatal error: thrift/lib/cpp2/util/MapCopy.h: No such file or directory

I manually copied the file to solve the problem.

Finally, everything is OK.

**Comment by apepojken** [comment]
[This patch](https://github.com/facebook/fbthrift/files/434265/fbthrift.zip) from @zleho fixes my issue. 
Thanks for the help!
